### ISSUE TITLE
Build on my arm platform failed | Failed to execute /runtime/target/pthreads-1.0.5 -> error=2, No such file or directory...

### ISSUE THREAD

**Issue by svencc** [appserver-io/appserver#617]
Hi,
I tried to start a build on my little ARM board (cubietruck/cubieboard3).

I installed open jdk 7 and I´m running a Debian System. I also installed the Ant buid tool.

I cloned a git copy of /runtime and executed ant in this Folder.
Here is the error which occured - any idea?

     [exec] Configuring extensions
     [exec] checking size of long... (cached) 4
     [exec] checking size of int... (cached) 4
     [exec] checking for int32_t... yes
     [exec] checking for uint32_t... yes
     [exec] checking for sys/types.h... (cached) yes
     [exec] checking for inttypes.h... (cached) yes
     [exec] checking for stdint.h... (cached) yes
     [exec] checking for string.h... (cached) yes
     [exec] checking for stdlib.h... (cached) yes
     [exec] checking for strtoll... yes
     [exec] checking for atoll... yes
     [exec] checking for strftime... (cached) yes
     [exec] checking which regex library to use... php
     [exec] checking whether to enable LIBXML support... yes
     [exec] checking libxml2 install dir... no
     [exec] checking for xml2-config path... /usr/bin/xml2-config
     [exec] checking whether libxml build works... yes
     [exec] checking for OpenSSL support... yes
     [exec] checking for Kerberos support... no
     [exec] checking for DSA_get_default_method in -lssl... yes
     [exec] checking for X509_free in -lcrypto... yes
     [exec] checking for pkg-config... /usr/bin/pkg-config
     [exec] checking for PCRE library to use... bundled
     [exec] checking whether to enable the SQLite3 extension... yes
     [exec] checking bundled sqlite3 library... yes
     [exec] checking for ZLIB support... yes
     [exec] checking if the location of ZLIB install directory is defined... no
     [exec] checking for zlib version >= 1.2.0.4... 1.2.7
     [exec] checking for gzgets in -lz... yes
     [exec] checking whether to enable AOP support... no
     [exec] checking whether to enable APCu support... no
     [exec] checking if APCu should provide APC full compatibility support... yes
     [exec] checking if APCu should be allowed to use rwlocks... yes
     [exec] checking if APCu should be built in debug mode... no
     [exec] checking if APCu should clear on SIGUSR1... no
     [exec] checking if APCu will use mmap or shm... mmap
     [exec] checking if APCu should utilize spinlocks before flocks... no
     [exec] checking whether to include code coverage symbols... no
     [exec] checking whether to enable appserver support... no
     [exec] checking whether to enable bc style precision math functions... yes, shared
     [exec] checking for BZip2 support... no
     [exec] checking whether to enable calendar conversion support... no
     [exec] checking whether to enable ctype functions... yes
     [exec] checking for cURL support... yes, shared
     [exec] checking for cURL in default path... found in /usr
     [exec] checking for cURL 7.10.5 or greater... libcurl 7.26.0
     [exec] checking for SSL support in libcurl... yes
     [exec] checking how to run the C preprocessor... cc -E
     [exec] checking for openssl support in libcurl... no
     [exec] checking for gnutls support in libcurl... no
     [exec] checking for curl_easy_perform in -lcurl... yes
     [exec] checking for curl_easy_strerror in -lcurl... yes
     [exec] checking for curl_multi_strerror in -lcurl... yes
     [exec] checking for QDBM support... no
     [exec] checking for GDBM support... no
     [exec] checking for NDBM support... no
     [exec] checking for TCADB support... no
     [exec] checking for Berkeley DB4 support... no
     [exec] checking for Berkeley DB3 support... no
     [exec] checking for Berkeley DB2 support... no
     [exec] checking for DB1 support... no
     [exec] checking for DBM support... no
     [exec] checking for CDB support... no
     [exec] checking for INI File support... no
     [exec] checking for FlatFile support... no
     [exec] checking whether to enable DBA interface... no
     [exec] checking whether to enable DOM support... yes
     [exec] checking for xml2-config path... (cached) /usr/bin/xml2-config
     [exec] checking whether libxml build works... (cached) yes
     [exec] checking for ENCHANT support... no
     [exec] checking whether to enable EXIF (metadata from images) support... no
     [exec] checking for fileinfo support... yes
     [exec] checking for utimes... yes
     [exec] checking for strndup... yes
     [exec] checking whether to enable input filter support... yes
     [exec] checking pcre install prefix... no
     [exec] checking whether to enable FTP support... no
     [exec] checking OpenSSL dir for FTP... /usr/lib
     [exec] checking for GD support... yes
     [exec] checking for the location of libvpx... no
     [exec] checking for the location of libjpeg... /usr
     [exec] checking for the location of libpng... /usr
     [exec] checking for the location of libXpm... no
     [exec] checking for FreeType 2... /usr
     [exec] checking for T1lib support... no
     [exec] checking whether to enable truetype string function in GD... no
     [exec] checking whether to enable JIS-mapped Japanese font support in GD... no
     [exec] If configure fails try --with-vpx-dir=<DIR>
     [exec] checking for jpeg_read_header in -ljpeg... yes
     [exec] checking for png_write_image in -lpng... yes
     [exec] If configure fails try --with-xpm-dir=<DIR>
     [exec] checking for fabsf... yes
     [exec] checking for floorf... yes
     [exec] checking for GNU gettext support... no
     [exec] checking for GNU MP support... no
     [exec] checking for mhash support... no
     [exec] checking whether to enable hash support... yes
     [exec] checking whether byte ordering is bigendian... (cached) no
     [exec] checking size of short... 2
     [exec] checking size of int... (cached) 4
     [exec] checking size of long... (cached) 4
     [exec] checking size of long long... (cached) 8
     [exec] checking for iconv support... yes
     [exec] checking for iconv... yes
     [exec] checking if iconv is glibc's... yes
     [exec] checking if iconv supports errno... yes
     [exec] checking if your cpp allows macro usage in include lines... yes
     [exec] checking for IMAP support... no
     [exec] checking for IMAP Kerberos support... no
     [exec] checking for IMAP SSL support... no
     [exec] checking for InterBase support... no
     [exec] checking whether to enable internationalization support... yes, shared
     [exec] checking for icu-config... /usr/bin/icu-config
     [exec] checking for location of ICU headers and libraries... /usr
     [exec] checking for ICU 4.0 or greater... found 4.8.1.1
     [exec] checking for g++... g++
     [exec] checking whether we are using the GNU C++ compiler... yes
     [exec] checking whether g++ accepts -g... yes
     [exec] checking how to run the C++ preprocessor... g++ -E
     [exec] checking whether to enable JavaScript Object Serialization support... yes
     [exec] checking for ANSI C header files... (cached) yes
     [exec] checking for LDAP support... yes
     [exec] checking for LDAP Cyrus SASL support... no
     [exec] checking size of long int... configure: error: Cannot find ldap libraries in /usr/lib.
     [exec] 4
     [exec] Result: 1
     [exec] make: *** No targets specified and no makefile found.  Stop.
     [exec] Result: 2
     [exec] make: *** No rule to make target `install'.  Stop.
     [exec] Result: 2

pecl-build-pthreads:
    [untar] Expanding: /home/sven/appserver.io/runtime/lib/pthreads-1.0.5.tgz into /home/sven/appserver.io/runtime/target

BUILD FAILED
/home/sven/appserver.io/runtime/build.xml:98: The following error occurred while executing this line:
/home/sven/appserver.io/runtime/buildfiles/linux/build.xml:184: The following error occurred while executing this line:
/home/sven/appserver.io/runtime/buildfiles/linux/build.xml:206: Execute failed: java.io.IOException: Cannot run program "/opt/appserver/bin/phpize" (in directory "/home/sven/appserver.io/runtime/target/pthreads-1.0.5"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:862)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:481)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:495)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:809)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 49 more

Total time: 3 minutes 32 seconds

**Comment by zelgerj** [comment]
Hi, seems like you don't have header-files for ldap-lib installed. Just give it a try with:
```bash
apt-get install libldb-dev
```

**Comment by svencc** [comment]
Hi!

thank you for the tip, but that did´t solve the Problem.

I recieve the same error: configure: error: Cannot find ldap libraries in /usr/lib.

I tried to install some other ldap and php libs(-dev) but I always get the same error. After searching the Internet I found out that this is a commen error while compiling php. 

Do you have any idea how to solve this?

**Comment by wick-ed** [comment]
Hi @svencc ,

I currently do not.
How did you execute the build?
Our default build will target Debian but also a x86_64/amd64 architecture.
So to get an ARM build you might have to change some values within `build.default.properties` or create a `build.properties` to overwrite the default values.

If you have the time then wait until I can retest your issue here, we currently do not have a spare ARM box but I can fetch one the next days.

**Comment by svencc** [comment]
Hi,
first things first: I try to build it like: $ ant build create-package

And "build.default.properties" looks like:
[...]
os.family = linux
os.distribution = debian
os.architecture = armv7l
[...]

If I run on the bash "$ arch"  ist tells me "armv71"
I´m running a Debian 7/Wheezy on cubieboard3 (also known as cubietruck - http://de.wikipedia.org/wiki/Cubieboard#Cubietruck_.2F_Cubieboard3)

http://de.wikipedia.org/wiki/Cubieboard#Cubietruck_.2F_Cubieboard3

If you look onto the error in Detail it says following:

BUILD FAILED
/home/sven/runtime/build.xml:98: The following error occurred while executing this line:
/home/sven/runtime/buildfiles/linux/build.xml:184: The following error occurred while executing this line:
/home/sven/runtime/buildfiles/linux/build.xml:206: Execute failed: java.io.IOException: CANNOT RUN PROGRAM "/opt/appserver/bin/phpize" (in directory "/home/sven/runtime/target/pthreads-1.0.5"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
[...]
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)

And yes he is totaly right if he tells me: "No such file or directory
/opt/appserver/bin/phpize"


/opt/.. is an empty directory on my machine, so the attempt to execute any binary from here cannot work...

May it possible that you configured your build in a way that it Needs this dependency?
Also, what can I do to solve this dependency?

**Comment by wick-ed** [comment]
It looks like PHP did not build correctly, that's why the process could not find `phpize`.
So you might focus on the location of your ldap libraries, maybe the script is looking in the wrong place.

**Comment by svencc** [comment]
Ah now I got the point!

First you need to configure in  /runtime/build.default.properties
os.architecture = arm           <- instead of  armv7l, armel or aarch64 or something other...

[optional]
After build failed once you need to remove the symlink: 
/usr/lib/libldap.so 
because it will point to <os.architecture>-linux-gnu/libldap.so, what was wrong maybe before!

For info, this symbolic link is created in:

runtime/buildfiles/linux/Debian/build.xml:
        
        <exec dir="/usr/lib" executable="ln">
                <arg value="-s"/>
                <arg value="${libldap.dir}/libldap.so"/>
        </exec>


Now this issue can be closed!
Thank you a lot!

In my Debian distribution the libldap.so we need is in /usr/lib/arm-linux-gnueabihf/libldap.so

BUT, the build script searches in arm-linux-gnu/libldap.so

This is configured in: /runtime/buildfiles/linux/Debian/build.default.properties

Where you have to fix this:

# ---- Path of the ldap lib -----------------------------------------------------
libldap.dir = ${os.architecture}-linux-gnu

to:

# ---- Path of the ldap lib -----------------------------------------------------
libldap.dir = ${os.architecture}-linux-gnueabihf

Now this issue can be closed,
thanks a lot!

**Comment by wick-ed** [comment]
Hi @svencc ,

that's great news. :)
The ldap path is kind of special for every OS, we faced similar issues when installing on my Raspberry running Raspbian.
I will extend the documentation in this regards so others can benefit from your work.

Thanks and have fun using appserver.io ;)
