### ISSUE TITLE
[appserver-io-php/runtime] ODROID-XU4 ARMv71 appserver.io build

### ISSUE THREAD

**Issue by kkeker** [appserver-io/appserver#946]
Hello! I use a computer with a processor ARMv71 and operating system Ubuntu-Server 14.04 LTS as I gather appserver.io for the platform? You have on the site are mainly the binaries as I can gather this system from source code or in part, from packages?

**Comment by wagnert** [comment]
Hi, if i understand you correctly, you want to build packages for a Linux distribution running on a ARMv71 processor, right? If yes, you would still have the possibility to checkout the latest stable version from this repository (tagged with 1.1.0), update the composer packages and have fun, assumed you have a PHP 5.6.x compiled with the `--enable-maintainer-zts` flag set. If not, you would have to build the PHP first. Hope that i could answer your questions :)

**Comment by kkeker** [comment]
This is information about my environment for the assembly:

root@odroid-server:~# php -v
PHP 5.6.17 (cli) (built: Jan 17 2016 12:36:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

root@odroid-server:~# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

root@odroid-server:~# ant -version
Apache Ant(TM) version 1.9.6 compiled on January 17 2016

root@odroid-server:~# composer.phar -V
Composer version 1.0-dev (42f49b3b979b7039d138e260d9087e93e46d715a) 2016-01-16 19:47:49

root@odroid-server:~# uname -a
Linux odroid-server 3.10.82 #1 SMP PREEMPT Tue Jul 14 01:28:23 BRT 2015 armv7l armv7l armv7l GNU/Linux

 use the documentation for http://appserver.io/get-started/documentation/1.0/installation.html Raspbian (though I use Ubuntu Server 14.04 for ARM) section "Building it yourself" and I have a problem.

I performed git clone https://github.com/appserver-io-php/runtime.git
But when the ant build voznimaet error:
root @ odroid-server: ~ / runtime # ant build
Buildfile: /root/runtime/build.xml

build:

start-vagrant-build-box:

clean:
   [delete] Deleting directory / root / runtime / target
   [delete] Deleting /root/runtime/tmp/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/mac/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/mac/scripts/build_openssl_dylib.sh
   [delete] Deleting /root/runtime/tmp/buildfiles/mac/scripts/build_openssl_dylib_x86_64.sh
   [delete] Deleting directory / root / runtime / tmp / buildfiles / mac / scripts
   [delete] Deleting /root/runtime/tmp/buildfiles/mac/build.default.properties
   [delete] Deleting directory / root / runtime / tmp / buildfiles / mac
   [delete] Deleting /root/runtime/tmp/buildfiles/win/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/win/scripts/prepare_php_sdk.bat
   [delete] Deleting /root/runtime/tmp/buildfiles/win/scripts/build_extensions.bat
   [delete] Deleting directory / root / runtime / tmp / buildfiles / win / scripts
   [delete] Deleting / root / runtime / tmp / buildfiles / win / Vagrantfile
   [delete] Deleting /root/runtime/tmp/buildfiles/win/build.default.properties
   [delete] Deleting /root/runtime/tmp/buildfiles/win/custom-lib/pthreadVC2.dll
   [delete] Deleting /root/runtime/tmp/buildfiles/win/custom-lib/php_pthreads-1.0.1.dll
   [delete] Deleting directory / root / runtime / tmp / buildfiles / win / custom-lib
   [delete] Deleting directory / root / runtime / tmp / buildfiles / win
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/centos/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/centos/7/build.default.properties
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / centos / 7
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/centos/provision.sh
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/centos/generic/build.default.properties
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / centos / generic
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / centos
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/8/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/8/build.default.properties
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/8/provision.sh
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / debian / 8
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/generic/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/generic/build.default.properties
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/debian/generic/provision.sh
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / debian / generic
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / debian
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/raspbian/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/raspbian/build.default.properties
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / raspbian
   [delete] Deleting / root / runtime / tmp / buildfiles / linux / Vagrantfile
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/build.default.properties
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/fedora/build.xml
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/fedora/build.default.properties
   [delete] Deleting /root/runtime/tmp/buildfiles/linux/fedora/provision.sh
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux / fedora
   [delete] Deleting directory / root / runtime / tmp / buildfiles / linux
   [delete] Deleting directory / root / runtime / tmp / buildfiles
   [delete] Deleting / root / runtime / tmp / Vagrantfile
   [delete] Deleting /root/runtime/tmp/build.properties
   [delete] Deleting directory / root / runtime / tmp / tmp
   [delete] Deleting directory / root / runtime / tmp

prepare:
    [mkdir] Created dir: / root / runtime / target
    [mkdir] Created dir: / root / runtime / tmp

prepare-build:

clean-build:

prepare-build-environment:
     [copy] Copying 33 files to / root / runtime / tmp
     [copy] Copying 1 file to / root / runtime / tmp
    [mkdir] Created dir: / root / runtime / tmp / tmp

test-vagrant-box-running:

BUILD FAILED
/root/runtime/vendor/package/common.xml:419: The following error occurred while executing this line:
/root/runtime/vendor/package/common.xml:245: The following error occurred while executing this line:
/root/runtime/vendor/package/common.xml:181: Execute failed: java.io.IOException: Can not run program "vagrant" (in directory "/ root / runtime / tmp"): error = 2, No such file or directory
        at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
        at java.lang.Runtime.exec (Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec (Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch (Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute (Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute (ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec (ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute (ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke (Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform (Task.java:348)
        at org.apache.tools.ant.Target.execute (Target.java:435)
        at org.apache.tools.ant.Target.performTasks (Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets (Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets (SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets (Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute (Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute (CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke (Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform (Task.java:348)
        at org.apache.tools.ant.Target.execute (Target.java:435)
        at org.apache.tools.ant.Target.performTasks (Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets (Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets (SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets (Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute (Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute (CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute (UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke (Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute (DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform (Task.java:348)
        at org.apache.tools.ant.Target.execute (Target.java:435)
        at org.apache.tools.ant.Target.performTasks (Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets (Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget (Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets (DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets (Project.java:1260)
        at org.apache.tools.ant.Main.runBuild (Main.java:853)
        at org.apache.tools.ant.Main.startAnt (Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run (Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main (Launcher.java:112)
Caused by: java.io.IOException: error = 2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec (Native Method)
        at java.lang.UNIXProcess. <init> (UNIXProcess.java:248)
        at java.lang.ProcessImpl.start (ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start (ProcessBuilder.java:1029)
        49 ... more

Total time: 2 seconds
root @ odroid-server: ~ / runtime #

**Comment by wick-ed** [comment]
Hi @kkeker ,

sorry about that. The docs to not reflect the latest changes to the build process.
We introduced a vagrant based abstraction layer for building for specific environments off of one build machine.
As this is not what you want please use `ant local-build` to build the project without the vagrant virtualization.
See also: https://github.com/appserver-io-dist/package#usage

If you encounter any errors again feel free to contact us again.
Please also report back if you were successful so we can close the issue.

Regards,

Bernhard

**Comment by kkeker** [comment]
[exec] Result: 1
     [exec] make: *** No targets specified and no makefile found.  Stop.
     [exec] Result: 2

run-php-tests:
     [exec] make: *** No rule to make target `install'.  Stop.
     [exec] Result: 2

pecl-build-pthreads:
    [untar] Expanding: /root/runtime/lib/pthreads-2.0.10.tgz into /root/runtime/target

BUILD FAILED
/root/runtime/build.xml:236: The following error occurred while executing this line:
/root/runtime/buildfiles/linux/build.xml:178: The following error occurred while executing this line:
/root/runtime/buildfiles/linux/build.xml:209: Execute failed: java.io.IOException: Cannot run program "/opt/appserver/bin/phpize" (in directory "/root/runtime/target/pthreads-2.0.10"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 49 more

Total time: 3 minutes 15 seconds
root@odroid-server:~/runtime#

**Comment by wick-ed** [comment]
Hi @kkeker 

it looks like building PHP failed.
Is there anything indicating that a dependency is unmet?
Can you post the output of the PHP environment tests?
I assume there will be a line along the lines of "Testing xyz support ...... No".

Regards,

Bernhard

**Comment by wick-ed** [comment]
Hi @kkeker ,

you still got problems with this issue? Or were you able to figure it out?
If not please provide the answers to the questions I wrote.

If everything is fine by now I would like to close the issue. :)

Regards,

Bernhard

**Comment by wick-ed** [comment]
Closed for being stale.
Please reopen if the issue still exists. :)
