### ISSUE TITLE
Appserver on mac osx, keep getting "Response already complete" page.

### ISSUE THREAD

**Issue by kailashgajara** [appserver-io/appserver#977]
Hi,

I have installed appserver appserver-dist_1.1.0-100_x86_64.pkg on my mac. Its running fine. But very often I get this error page with following stack trace:

Response already complete
exception 'AppserverIo\Server\Exceptions\ModuleException' with message 'Response already complete' in /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/Modules/FastCgiModule.php:156
Stack trace:
#0 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(507): AppserverIo\WebServer\Modules\FastCgiModule->process(Object(AppserverIo\Http\HttpRequest), Object(AppserverIo\Http\HttpResponse), Object(AppserverIo\Server\Contexts\RequestContext), 2)

#1 /opt/appserver/vendor/appserver-io/webserver/src/AppserverIo/WebServer/ConnectionHandlers/HttpConnectionHandler.php(433): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->processModules(2)

#2 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(256): AppserverIo\WebServer\ConnectionHandlers\HttpConnectionHandler->handle(Object(AppserverIo\Server\Sockets\StreamSocket), Object(AppserverIo\Server\Workers\ThreadWorker))

#3 /opt/appserver/vendor/appserver-io/server/src/AppserverIo/Server/Workers/ThreadWorker.php(183): AppserverIo\Server\Workers\ThreadWorker->work()

#4 {main}

**Comment by wagnert** [comment]
@kailashgajara Did you also face that problem with 1.1.1 or 1.1.2? Or can you give us more information about the request that leads to the error message?
